apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: healthcare
        image: pushpakumari1/myimage:23
        ports:
        - containerPort: 8080
